### ISSUE TITLE
Could you please opensource the code?

### ISSUE THREAD

**Issue by RainyLave** [Tingwuren/GaomonTablet_M7_LinuxDriver#1]
Hello, thanks to your work, now I can run tablet M7 on my ubuntu well. However, I still wants to transplant this project on my old iOS system so that I can run my M7 tablet on my old iOS devices, I wonder if  you can provide  the source code so that I can trying this? Thanks a lot!

**Comment by Tingwuren** [comment]
I'm sorry that I don't have the source code for this project. I downloaded the M1230 driver from https://download.gaomon.net/. I noticed that the website has Mac, Windows and Linux versions, but I didn't notice the IOS version. You can consult GAOMON officials for help.

**Comment by RainyLave** [comment]
OK, Tks a lot!
